apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-chat-app
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: ararso1/django-chat
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: djangonew
spec:
  selector:
    app: django  # Updated selector to match the deployment label
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8000
    nodePort: 31110
