version: '3'

services:
    web:
      build: ./app
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - 8000:8000
      env_file:   
        - ./.env.dev
      depends_on:
        - db
      environment:
        - POSTGRES_USER=chatapp
        - POSTGRES_PASSWORD=chatapp
        - POSTGRES_DB=chatapp_dev

    db:
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:   
        - ./.env.dev.db
      environment:
        - POSTGRES_USER=chatapp
        - POSTGRES_PASSWORD=chatapp
        - POSTGRES_DB=chatapp_dev

volumes:
  postgres_data: