version: '3'

services:
  web:
    build: .
    command: gunicorn PyChat.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    environment:
      - POSTGRES_USER=chatapp
      - POSTGRES_PASSWORD=chatapp
      - POSTGRES_DB=chatapp_prod
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    environment:
      - POSTGRES_USER=chatapp
      - POSTGRES_PASSWORD=chatapp
      - POSTGRES_DB=chatapp_prod

volumes:
  postgres_data: