# Generated by Django 4.0.3 on 2022-11-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostPage',
        ),
    ]
