# Generated by Django 4.0.3 on 2022-11-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0005_alter_chatroom_id_alter_friends_id_alter_messages_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='text',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
