# Generated by Django 4.0.3 on 2022-11-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0006_alter_chatmessage_text_alter_postpage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='home',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
