# Generated by Django 4.0.3 on 2022-11-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0007_postpage_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpage',
            old_name='date',
            new_name='posted_date',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='home',
        ),
    ]
