# Generated by Django 4.0.3 on 2022-12-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0008_rename_date_postpage_posted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
